name: hfullest 服务器项目发布

on:
  push:
    tags: ["v*"]
  pull_request:
    tags: ["v*"]
  workflow_dispatch:

jobs:
  Build-Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取远程代码
        uses: actions/checkout@v3
        with:
          fetch-depth: "0"
      - name: 配置 pnpm 环境
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 7.26.2
      - name: 设置 node 配置
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          cache: "pnpm"
      - name: 安装依赖
        run: pnpm install
      - name: 项目编译打包并输出
        run: pnpm build
      - name: 准备远程部署目录
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER_NAME }}
          password: ${{ secrets.PASSWORD }}
          script: temp=~/projects/.temp &&
            rm -rf $temp &&
            mkdir -p $temp
      - name: 复制文件到远程
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER_NAME }}
          password: ${{ secrets.PASSWORD }}
          rm: true
          source: "dist/*"
          target: "~/projects/.temp"
      - name: 执行远程脚本命令
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER_NAME }}
          password: ${{ secrets.PASSWORD }}
          script: origin_pwd=$(pwd) &&
            base_path=~/projects &&
            temp_dir=$base_path/.temp &&
            rep_url=${{ github.repositoryUrl }} &&
            pos_path=$(node -p "\`$rep_url\`.match(/\/\/[^/]*(\/.*)(\.[^.]*?)$/)?.[1]") &&
            absolute_path=$base_path/$pos_path &&
            mkdir -p $absolute_path &&
            echo "项目完整路径：$absolute_path" &&
            cd $temp_dir &&
            mkdir -p $absolute_path &&
            cp -r $temp_dir/* $absolute_path &&
            rm -rf $temp_dir &&
            cd $absolute_path &&
            deploy_exist=$(node -p "require('./package.json')?.scripts?.deploy ??''") &&
            if [ "$deploy_exist" ]; then pnpm run deploy; fi &&
            cd $origin_pwd
      - name: 部署完成
        run: echo "项目部署完成！"
