name: hfullest 服务器项目发布

on:
  push:
    tags: ["v*"]
  pull_request:
    tags: ["v*"]
  workflow_dispatch:

jobs:
  Build-Deploy:
    runs-on: ubuntu-latest
    env:
      gitURL: git@github.com
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7.21.0
      - name: 设置 node 配置
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          cache: "pnpm"
      - name: 执行远程脚本命令
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER_NAME }}
          password: ${{ secrets.PASSWORD }}
          script: origin_pwd=$(pwd) &&
            base_path=~/projects &&
            rep_url=${{ github.repositoryUrl }} &&
            pos_path=$(node -p "\`$rep_url\`.match(/\/\/[^/]*(\/.*)(\.[^.]*?)$/)?.[1]") &&
            absolute_path=$base_path/$pos_path &&
            mkdir -p $absolute_path &&
            echo "项目完整路径：$absolute_path" &&
            cd $absolute_path &&
            git_repo=$gitURL:${{ github.repository }} &&
            git init &&
            remote_origin=$(git remote -v | grep origin) &&
            if [ "$remote_origin" ]; then git remote add origin $git_repo &&
            git pull origin master &&
            pnpm docs:build &&
            echo "项目拉取完成" &&
            deploy_exist=$(node -p "require('./package.json')?.scripts?.deploy ??''") &&
            if [ "$deploy_exist" ]; then pnpm run deploy; fi &&
            cd $origin_pwd
      - run: echo "项目部署完成！"
